added fisrt task module 2
js-tasks-ru/jsbasic-20201008_allanehaenko pull request #3
Opened 2020-10-17 07:50 UTC by Nehaenko

2020-10-17 08:01 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Определите, пуст ли объект
+ объект с удалённым свойством - пустой
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
+ если у объекта есть хоть одно свойство, то он не пустой
```
```diff
Функция sumSalary(salaries)
+ должна игнорировать свойства других типов
+ должна складывать все зарплаты
+ должна возвращать 0 если нет свойств с зарплатами
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-10-17 12:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @stas-dolgachov

2020-10-19 10:29 UTC, stas-dolgachov requested changes

2020-10-19 10:29 UTC, stas-dolgachov commented on 2-module/1-task/index.js
> +  delete salaries.month;
Удалять свойства в этом слукчае, плохая идея. 
Ведь мы не хотим, чтобы после работы нашей функции объект был изменен. 
Вы не могли бы попробовать иначе решить эту задачу?
Напишите мне, пожалуйста, в личные сообщения в Слаке если у вас будут вопросы.

2020-10-19 10:29 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  read() {
👍

2020-10-19 18:02 UTC, Nehaenko commented on 2-module/1-task/index.js
> +  delete salaries.month;
Решение поменяла, спасибо за комментарий

2020-10-19 18:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @stas-dolgachov

2020-10-20 10:45 UTC, stas-dolgachov approved these changes

2020-10-20 10:45 UTC, merged